In [1]:
# Importing NumPy
import numpy as np

# 16. Indexing with Boolean Arrays
array = np.array([10, 20, 30, 40, 50])

# Create a boolean mask
mask = array > 30

# Use the mask to filter values
filtered_array = array[mask]

print("Original Array:", array)
print("Boolean Mask:", mask)
print("Filtered Array:", filtered_array)

print("\n")  # Add space between sections

# 17. Fancy Indexing
array = np.array([10, 20, 30, 40, 50])

# Selecting elements at specific indices
selected_elements = array[[0, 2, 4]]

print("Original Array:", array)
print("Selected Elements:", selected_elements)

print("\n")  # Add space between sections

# 18. Data Type Conversion
array = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Convert to float
converted_array = array.astype(np.float64)

print("Original Array (int32):", array)
print("Converted Array (float64):", converted_array)

print("\n")  # Add space between sections

# 19. Stacking and Splitting Arrays
# Stacking arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

stacked_vertical = np.vstack((array1, array2))
stacked_horizontal = np.hstack((array1, array2))

print("Stacked Vertically:\n", stacked_vertical)
print("Stacked Horizontally:\n", stacked_horizontal)

# Splitting arrays
array = np.array([1, 2, 3, 4, 5, 6])
split_arrays = np.split(array, 3)

print("Split Arrays:", split_arrays)

print("\n")  # Add space between sections

# 20. Broadcasting in Operations
# Broadcasting a scalar to a 1D array
array = np.array([1, 2, 3])
scalar = 10
result = array + scalar

print("Array:", array)
print("Scalar:", scalar)
print("Broadcasting Result:", result)

# Broadcasting a smaller array to a larger one
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])
broadcast_result = matrix + row

print("Matrix:\n", matrix)
print("Row:", row)
print("Broadcasting Result:\n", broadcast_result)


Original Array: [10 20 30 40 50]
Boolean Mask: [False False False  True  True]
Filtered Array: [40 50]


Original Array: [10 20 30 40 50]
Selected Elements: [10 30 50]


Original Array (int32): [1 2 3 4 5]
Converted Array (float64): [1. 2. 3. 4. 5.]


Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally:
 [1 2 3 4 5 6]
Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]


Array: [1 2 3]
Scalar: 10
Broadcasting Result: [11 12 13]
Matrix:
 [[1 2 3]
 [4 5 6]]
Row: [10 20 30]
Broadcasting Result:
 [[11 22 33]
 [14 25 36]]
