In [1]:
# Importing NumPy
import numpy as np

# 21. Masking and Conditional Logic
array = np.array([1, 2, 3, 4, 5, 6])

# Create a mask for values greater than 3
mask = array > 3

# Use the mask to filter elements
filtered_array = array[mask]

# Modify elements based on a condition
modified_array = np.where(array > 3, array * 10, array)

print("Original Array:", array)
print("Mask (values > 3):", mask)
print("Filtered Array (values > 3):", filtered_array)
print("Modified Array (values > 3 multiplied by 10):", modified_array)

print("\n")  # Add space between sections

# 22. Structured Arrays
# Define a structured data type
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

# Create a structured array
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5), ('Cathy', 22, 50.2)], dtype=data_type)

# Access specific fields
names = people['name']
ages = people['age']
weights = people['weight']

print("Structured Array:\n", people)
print("Names:", names)
print("Ages:", ages)
print("Weights:", weights)

print("\n")  # Add space between sections

# 23. Saving and Loading Arrays
# Create an array
array = np.array([1, 2, 3, 4, 5])

# Save to a file
np.save('array_file.npy', array)

# Load from the file
loaded_array = np.load('array_file.npy')

print("Original Array:", array)
print("Loaded Array:", loaded_array)

print("\n")  # Add space between sections

# 24. Matrix Operations
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
matrix_product = np.dot(matrix1, matrix2)

# Transpose of a matrix
matrix_transpose = matrix1.T

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Product:\n", matrix_product)
print("Transpose of Matrix 1:\n", matrix_transpose)

print("\n")  # Add space between sections

# 25. Element-Wise Comparisons
array1 = np.array([1, 2, 3])
array2 = np.array([3, 2, 1])

# Element-wise comparisons
equal = array1 == array2
greater = array1 > array2
less = array1 < array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Equal:", equal)
print("Greater:", greater)
print("Less:", less)


Original Array: [1 2 3 4 5 6]
Mask (values > 3): [False False False  True  True  True]
Filtered Array (values > 3): [4 5 6]
Modified Array (values > 3 multiplied by 10): [ 1  2  3 40 50 60]


Structured Array:
 [('Alice', 25, 55. ) ('Bob', 30, 85.5) ('Cathy', 22, 50.2)]
Names: ['Alice' 'Bob' 'Cathy']
Ages: [25 30 22]
Weights: [55.  85.5 50.2]


Original Array: [1 2 3 4 5]
Loaded Array: [1 2 3 4 5]


Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matrix Product:
 [[19 22]
 [43 50]]
Transpose of Matrix 1:
 [[1 3]
 [2 4]]


Array 1: [1 2 3]
Array 2: [3 2 1]
Equal: [False  True False]
Greater: [False False  True]
Less: [ True False False]
