In [12]:
# Chapter 2: Introduction to NumPy

# 1. Importing NumPy
import numpy as np



In [ ]:
# 2. Creating Arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


In [ ]:
# 3. Basic Operations
array = np.array([1, 2, 3, 4, 5])
print(array + 5)
print(array * 2)
print(np.sum(array))


In [ ]:
# 4. Array Attributes
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", array.shape)
print("Size:", array.size)
print("Data type:", array.dtype)


In [ ]:
# 5. Indexing and Slicing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[0, 1])
print(matrix[0])
print(matrix[:, 1])
print(matrix[:2, :2])


In [ ]:
# 6. Matrix Multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)


In [ ]:
# 7. Array Broadcasting
matrix = np.array([[1, 2], [3, 4]])
scalar = 10
result = matrix + scalar
print(result)


In [ ]:
# 8. Reshaping Arrays
array = np.arange(1, 7)
reshaped = array.reshape(2, 3)
print(reshaped)
flattened = reshaped.flatten()
print(flattened)


In [14]:
# 9. Combining Arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
vertical = np.vstack((array1, array2))
print(vertical)
horizontal = np.hstack((array1, array2.T))
print(horizontal)


[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [13]:
# 10. Boolean Masking
array = np.array([1, 2, 3, 4, 5, 6])
mask = array > 3
filtered = array[mask]
print(filtered)


[4 5 6]
