In [1]:
# Importing NumPy
import numpy as np

# 11. Mathematical Functions
array = np.array([1, 2, 3, 4, 5])

# Applying mathematical functions
squared = np.square(array)
sqrt = np.sqrt(array)
sin_values = np.sin(array)
log_values = np.log(array)

print("Original Array:", array)
print("Squared:", squared)
print("Square Root:", sqrt)
print("Sine Values:", sin_values)
print("Logarithm Values:", log_values)

print("\n")  # Add space between sections

# 12. Random Number Generation
# Random integers
random_ints = np.random.randint(1, 10, size=(3, 3))

# Random floats
random_floats = np.random.rand(3, 3)

# Normal distribution
random_normal = np.random.normal(0, 1, size=(3, 3))

print("Random Integers:\n", random_ints)
print("\nRandom Floats:\n", random_floats)
print("\nRandom Normal Distribution:\n", random_normal)

print("\n")  # Add space between sections

# 13. Sorting and Unique Values
array = np.array([5, 2, 9, 1, 5, 6, 7, 8, 2])

# Sorting the array
sorted_array = np.sort(array)

# Finding unique values
unique_values = np.unique(array)

print("Original Array:", array)
print("Sorted Array:", sorted_array)
print("Unique Values:", unique_values)

print("\n")  # Add space between sections

# 14. Aggregations
array = np.array([1, 2, 3, 4, 5])

# Aggregate functions
total_sum = np.sum(array)
average = np.mean(array)
max_value = np.max(array)
min_value = np.min(array)

print("Original Array:", array)
print("Sum:", total_sum)
print("Mean:", average)
print("Max:", max_value)
print("Min:", min_value)

print("\n")  # Add space between sections

# 15. Linear Algebra
matrix = np.array([[1, 2], [3, 4]])

# Determinant
determinant = np.linalg.det(matrix)

# Inverse
inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:\n", matrix)
print("Determinant:", determinant)
print("Inverse Matrix:\n", inverse_matrix)


Original Array: [1 2 3 4 5]
Squared: [ 1  4  9 16 25]
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Sine Values: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Logarithm Values: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


Random Integers:
 [[4 6 2]
 [1 3 8]
 [6 4 2]]

Random Floats:
 [[0.42412775 0.44216436 0.50191441]
 [0.62992344 0.92680037 0.3421583 ]
 [0.04982693 0.05578832 0.52794708]]

Random Normal Distribution:
 [[-0.02344729  0.37126128 -0.49334782]
 [ 0.11384361 -1.1570536   1.53200437]
 [ 1.82618201 -0.04712283  0.12525846]]


Original Array: [5 2 9 1 5 6 7 8 2]
Sorted Array: [1 2 2 5 5 6 7 8 9]
Unique Values: [1 2 5 6 7 8 9]


Original Array: [1 2 3 4 5]
Sum: 15
Mean: 3.0
Max: 5
Min: 1


Original Matrix:
 [[1 2]
 [3 4]]
Determinant: -2.0000000000000004
Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
