In [9]:
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Arithmetic operations
print("Array * 2:", array * 2)
print("Array + 10:", array + 10)
print("Sum of all elements:", np.sum(array))
print("Mean value:", np.mean(array))

Array * 2: [ 2  4  6  8 10]
Array + 10: [11 12 13 14 15]
Sum of all elements: 15
Mean value: 3.0


In [2]:
import numpy as np

# Creating a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements
print("First row:", matrix[0])
print("Element (2,3):", matrix[1, 2])

# Transposition
print("Transposed matrix:")
print(matrix.T)

# Sum by rows and columns
print("Sum by rows:", matrix.sum(axis=1))
print("Sum by columns:", matrix.sum(axis=0))

First row: [1 2 3]
Element (2,3): 6
Transposed matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum by rows: [ 6 15 24]
Sum by columns: [12 15 18]
