In [2]:
import numpy as np

# Creating two 2D matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.dot(matrix1, matrix2)
print("Matrix multiplication result:\n", result)

Matrix multiplication result:
 [[19 22]
 [43 50]]


In [9]:
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Calculating statistical values
print("Maximum value of the array:", np.max(array))  # maximum
print("Minimum value of the array:", np.min(array))  # minimum
print("Mean value of the array:", np.mean(array))  # mean
print("Median value of the array:", np.median(array))  # median
print("Standard deviation of the array:", np.std(array))  # standard deviation

Maximum value of the array: 9
Minimum value of the array: 1
Mean value of the array: 5.0
Median value of the array: 5.0
Standard deviation of the array: 2.581988897471611


In [6]:
import numpy as np

# Creating an array of random numbers
random_array = np.random.rand(3, 4)  # 3x4 array with random numbers between 0 and 1
print("Array of random numbers:\n", random_array)

# Generating random integers
random_int_array = np.random.randint(1, 10, size=(3, 3))  # 3x3 array of integers between 1 and 10
print("Array of random integers:\n", random_int_array)

Array of random numbers:
 [[0.30412594 0.97163763 0.25935435 0.92052177]
 [0.63486423 0.16216839 0.18132435 0.06472154]
 [0.66591028 0.60417231 0.79000426 0.77378944]]
Array of random integers:
 [[8 9 1]
 [4 6 1]
 [8 8 9]]
