In [5]:
# Chapter 2: Introduction to NumPy

# 1. Importing NumPy
import numpy as np

# 2. Creating Arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("\n")  # Add some space between sections

# 3. Basic Operations
array = np.array([1, 2, 3, 4, 5])
print("Basic Operations: ", array + 5)
print(array * 2)
print(np.sum(array))

print("\n")  # Add some space between sections

# 4. Array Attributes
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array Shape:", array.shape)
print("Array Size:", array.size)
print("Array Data Type:", array.dtype)

print("\n")  # Add some space between sections

# 5. Indexing and Slicing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Indexing and Slicing:")
print(matrix[0, 1])  # Indexing an element
print(matrix[0])  # Accessing a row
print(matrix[:, 1])  # Accessing a column
print(matrix[:2, :2])  # Slicing a part of the matrix

print("\n")  # Add some space between sections

# 6. Matrix Multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print("Matrix Multiplication Result:", result)

print("\n")  # Add some space between sections

# 7. Array Broadcasting
matrix = np.array([[1, 2], [3, 4]])
scalar = 10
result = matrix + scalar
print("Array Broadcasting Result:", result)

print("\n")  # Add some space between sections

# 8. Reshaping Arrays
array = np.arange(1, 7)
reshaped = array.reshape(2, 3)
print("Reshaped Array:\n", reshaped)
flattened = reshaped.flatten()
print("Flattened Array:", flattened)

print("\n")  # Add some space between sections

# 9. Combining Arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
vertical = np.vstack((array1, array2))
print("Vertical Stack:\n", vertical)
horizontal = np.hstack((array1, array2.T))
print("Horizontal Stack:\n", horizontal)

print("\n")  # Add some space between sections

# 10. Boolean Masking
array = np.array([1, 2, 3, 4, 5, 6])
mask = array > 3
filtered = array[mask]
print("Boolean Masking Result:", filtered)




Basic Operations:  [ 6  7  8  9 10]
[ 2  4  6  8 10]
15


Array Shape: (2, 3)
Array Size: 6
Array Data Type: int64


Indexing and Slicing:
2
[1 2 3]
[2 5 8]
[[1 2]
 [4 5]]


Matrix Multiplication Result: [[19 22]
 [43 50]]


Array Broadcasting Result: [[11 12]
 [13 14]]


Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]]
Horizontal Stack:
 [[1 2 5]
 [3 4 6]]


Boolean Masking Result: [4 5 6]
